"use client";
import { useEffect, useRef, useState } from 'react';

type Question={id:string;prompt:string;options:string[];answer:number;explanation:string};
const questions:Question[]=[
 {id:'equation',prompt:'A business has assets of ₦900,000 and liabilities of ₦350,000. What is its equity?',options:['₦350,000','₦550,000','₦900,000','₦1,250,000'],answer:1,explanation:'Equity = assets − liabilities. ₦900,000 − ₦350,000 = ₦550,000.'},
 {id:'credit',prompt:'Equipment is purchased for ₦200,000 on credit. What is the immediate effect on the accounting equation?',options:['Assets and liabilities both increase by ₦200,000','Assets increase and equity decreases by ₦200,000','Assets decrease and liabilities increase by ₦200,000','Only liabilities increase by ₦200,000'],answer:0,explanation:'The equipment increases assets. The amount owed to the supplier increases liabilities by the same amount.'},
 {id:'gross-profit',prompt:'Revenue is ₦800,000 and cost of sales is ₦500,000. What is the gross profit?',options:['₦1,300,000','₦500,000','₦300,000','₦800,000'],answer:2,explanation:'Gross profit = revenue − cost of sales. ₦800,000 − ₦500,000 = ₦300,000. Other operating expenses have not yet been deducted.'},
 {id:'receivable',prompt:'A customer pays ₦60,000 that was already recorded as a receivable. Which entry records the receipt?',options:['Debit revenue; credit cash','Debit receivables; credit revenue','Debit cash; credit revenue','Debit cash; credit receivables'],answer:3,explanation:'Cash increases, so debit cash. The customer’s outstanding balance falls, so credit receivables. The receipt does not create new revenue.'},
 {id:'depreciation',prompt:'An asset costs ₦500,000, has an estimated residual value of ₦50,000 and a useful life of five years. What is one full year of straight-line depreciation?',options:['₦100,000','₦90,000','₦110,000','₦50,000'],answer:1,explanation:'Annual depreciation = (cost − residual value) ÷ useful life. (₦500,000 − ₦50,000) ÷ 5 = ₦90,000.'},
];

export function PracticeRoom(){
 const [phase,setPhase]=useState<'setup'|'active'|'confirm'|'results'>('setup');
 const [mode,setMode]=useState<'practice'|'timed'>('practice');
 const [minutes,setMinutes]=useState(5);
 const [items,setItems]=useState(questions);
 const [answers,setAnswers]=useState<Record<string,number>>({});
 const [flags,setFlags]=useState<string[]>([]);
 const [index,setIndex]=useState(0);
 const [deadline,setDeadline]=useState<number|null>(null);
 const [remaining,setRemaining]=useState(0);
 const [expired,setExpired]=useState(false);
 const deadlineRef=useRef<number|null>(null);
 const active=phase==='active'||phase==='confirm';
 useEffect(()=>{
  if(!active||deadline===null)return;
  const tick=()=>{const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));setRemaining(left);if(left===0){setExpired(true);setPhase('results');}};
  tick();const id=setInterval(tick,250);return()=>clearInterval(id);
 },[active,deadline]);
 useEffect(()=>{if(!active)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[active]);
 const answerCount=items.filter(q=>answers[q.id]!==undefined).length;
 const score=items.filter(q=>answers[q.id]===q.answer).length;
 const missed=items.filter(q=>answers[q.id]!==q.answer);
 const start=(set:Question[])=>{setItems(set);setAnswers({});setFlags([]);setIndex(0);setExpired(false);const end=mode==='timed'?Date.now()+minutes*60000:null;deadlineRef.current=end;setDeadline(end);setRemaining(minutes*60);setPhase('active');};
 const choose=(id:string,value:number)=>{if(deadlineRef.current!==null&&Date.now()>=deadlineRef.current){setExpired(true);setPhase('results');return;}setAnswers(old=>({...old,[id]:value}));};
 const question=items[index];
 return <section className="quiz-room" aria-label="Practice and quizzes">
  <div className="quiz-label">DIET PRACTICE LAB <span>Sample question set</span></div>
  <h2 className="quiz-title">{phase==='results'?'Let’s review your attempt.':phase==='setup'?'A little practice. A clearer picture.':'Accounting warm-up'}</h2>
  <p className="quiz-disclaimer">Five original introductory accounting questions to try the quiz experience. This is not an ICAN past paper or a full mock exam. Attempts are temporary and do not update your learning report.</p>
  {phase==='setup'?<div className="quiz-setup"><div className="quiz-set"><span className="subject-eyebrow">ACCOUNTING FUNDAMENTALS</span><h3>Start with the basics</h3><p>Accounting equation, double entry, gross profit and depreciation.</p><div className="quiz-facts"><span>5 questions</span><span>Multiple choice</span><span>Explanations after submission</span></div><div className="quiz-cover">PRACTICE IMAGE</div></div><div className="quiz-settings"><h3>Choose how to practise</h3><label className="quiz-mode"><input type="radio" name="quiz-mode" checked={mode==='practice'} onChange={()=>setMode('practice')}/><span><strong>At your own pace</strong><small>No timer. Review your answers before submitting.</small></span></label><label className="quiz-mode"><input type="radio" name="quiz-mode" checked={mode==='timed'} onChange={()=>setMode('timed')}/><span><strong>Timed practice</strong><small>Answers are submitted when time runs out.</small></span></label>{mode==='timed'&&<label className="quiz-duration">Time allowed<select value={minutes} onChange={e=>setMinutes(Number(e.target.value))}><option value={1}>1 minute · quick demo</option><option value={5}>5 minutes</option><option value={10}>10 minutes</option></select></label>}<button className="subject-primary" onClick={()=>start(questions)}>Start sample practice →</button><p className="subject-note">Stay on this page during an attempt. Refreshing or leaving clears it.</p></div></div>:phase==='results'?<>
   <div className="quiz-results" role="status"><div><span className="subject-eyebrow">{expired?'TIME IS UP':'ATTEMPT COMPLETE'}</span><strong>{score}<small> / {items.length}</small></strong><p>{Math.round(score/items.length*100)}% correct</p></div><div><h3>{score===items.length?'Every answer correct.':'Your next step is in the review.'}</h3><p>{items.length-answerCount} unanswered · {answerCount-score} incorrect</p><p>Use the explanations below to check your reasoning.</p></div></div><div className="quiz-result-actions"><button className="subject-primary" onClick={()=>start(questions)}>Try the full sample again</button>{missed.length>0&&<button className="quiz-secondary" onClick={()=>start(missed)}>Retry missed questions ({missed.length})</button>}<button className="quiz-secondary" onClick={()=>{setDeadline(null);deadlineRef.current=null;setPhase('setup');}}>Change practice mode</button></div><h3 className="quiz-review-title">Answer review</h3><div className="quiz-review">{items.map((q,i)=><article key={q.id}><div><span className={`quiz-result-tag ${answers[q.id]===q.answer?'correct':''}`}>{answers[q.id]===q.answer?'Correct':answers[q.id]===undefined?'Unanswered':'Incorrect'}</span><h4>{i+1}. {q.prompt}</h4></div><p><b>Your answer:</b> {answers[q.id]===undefined?'No answer selected':q.options[answers[q.id]]}</p><p><b>Correct answer:</b> {q.options[q.answer]}</p><div className="quiz-explanation">{q.explanation}</div></article>)}</div>
  </>:<><div className="quiz-status"><span>{answerCount} of {items.length} answered</span>{mode==='timed'?<strong className={remaining<=30?'quiz-urgent':''} role="timer" aria-label="Time remaining">{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} remaining</strong>:<strong>At your own pace</strong>}</div><progress aria-label="Questions answered" value={answerCount} max={items.length}/>{phase==='confirm'?<section className="quiz-confirm"><h3>Ready to submit?</h3><p>{items.length-answerCount?`${items.length-answerCount} unanswered question(s) will score zero.`:'You have answered every question.'} {flags.length} flagged for review.</p><div><button className="subject-primary" onClick={()=>{if(deadlineRef.current!==null&&Date.now()>=deadlineRef.current)setExpired(true);setPhase('results');}}>Submit answers</button><button className="quiz-secondary" onClick={()=>setPhase('active')}>Keep reviewing</button></div></section>:<div className="quiz-active"><div className="quiz-question"><div className="quiz-question-head"><span className="subject-eyebrow">QUESTION {index+1} OF {items.length}</span><button aria-pressed={flags.includes(question.id)} onClick={()=>setFlags(old=>old.includes(question.id)?old.filter(id=>id!==question.id):[...old,question.id])}>{flags.includes(question.id)?'Flagged for review':'Flag for review'}</button></div><fieldset><legend>{question.prompt}</legend>{question.options.map((option,i)=><label className={`quiz-option ${answers[question.id]===i?'selected':''}`} key={option}><input type="radio" name={question.id} checked={answers[question.id]===i} onChange={()=>choose(question.id,i)}/><span className="quiz-letter">{String.fromCharCode(65+i)}</span><span>{option}</span></label>)}</fieldset><div className="quiz-nav"><button className="quiz-secondary" disabled={index===0} onClick={()=>setIndex(i=>i-1)}>← Previous</button>{index<items.length-1?<button className="subject-primary" onClick={()=>setIndex(i=>i+1)}>Next question →</button>:<button className="subject-primary" onClick={()=>setPhase('confirm')}>Review & submit</button>}</div></div><aside className="quiz-map"><h3>Your questions</h3><div>{items.map((q,i)=><button key={q.id} aria-label={`Question ${i+1}${answers[q.id]!==undefined?', answered':''}${flags.includes(q.id)?', flagged':''}`} aria-current={i===index?'step':undefined} className={answers[q.id]!==undefined?'answered':''} onClick={()=>setIndex(i)}>{i+1}{flags.includes(q.id)&&<span aria-hidden="true">*</span>}</button>)}</div><p>Green = answered<br/>* = flagged for review</p><button className="quiz-secondary" onClick={()=>setPhase('confirm')}>Review & submit</button></aside></div>}</>}
 </section>;
}
