"use client";
import Link from 'next/link';
import { useState } from 'react';
import type { TrackerState } from '@/lib/types';
import { getStudent, getStudentPapers, getStudentProgress } from '@/lib/selectors';
import { stageFor } from '@/lib/stages';
const features=[
 {tag:'YOUR NEXT EXAM STARTS HERE',title:'A clear plan.\nA confident next step.',body:'Choose a subject, work through a topic, and keep your preparation moving.',action:'Explore my subjects',destination:'#home-subjects',art:'FEATURE IMAGE'},
 {tag:'MAKE ROOM FOR PRACTICE',title:'Know it.\nThen put it to work.',body:'Track the questions you have attempted and give difficult topics another look.',action:'Open practice room',destination:'/dashboard?view=practice',art:'PRACTICE IMAGE'},
 {tag:'ONE WEEK AT A TIME',title:'Small steps.\nSteady progress.',body:'Choose a few priorities for the week and give each one your attention.',action:'Plan my week',destination:'/dashboard?view=weekly',art:'STUDY IMAGE'},
];
export function StudentHomepage({state,studentId,preview=false}:{state:TrackerState;studentId:string;preview?:boolean}) {
 const [slide,setSlide]=useState(0),[search,setSearch]=useState('');
 const student=getStudent(state,studentId); if(!student)return <p>Your profile could not be loaded.</p>;
 const papers=getStudentPapers(state,studentId), progress=getStudentProgress(state,studentId);
 const recent=[...progress].filter(p=>p.status!=='Not Started'||p.lastStudied).sort((a,b)=>(b.lastStudied??b.updatedAt).localeCompare(a.lastStudied??a.updatedAt))[0];
 const recentTopic=recent?state.topics.find(t=>t.id===recent.topicId):null;
 const recentPaper=recentTopic?papers.find(p=>p.id===recentTopic.paperId):null;
 const weekly=progress.filter(p=>p.thisWeek), confident=progress.filter(p=>p.status==='Okay').length;
 const filtered=papers.filter(p=>`${p.code} ${p.name}`.toLowerCase().includes(search.trim().toLowerCase()));
 const stage=stageFor(student.level)??student.level;
 const href=(url:string)=>preview&&!url.startsWith('#')?(url.startsWith('/papers/')?`/login?mode=preview&stage=${encodeURIComponent(stage)}&subject=${encodeURIComponent(url.slice(8))}`:'/login'):url;
 const feature=features[slide];
 return <div className="learning-home">
  <header className="home-welcome"><div><p>YOUR LEARNING HOME</p><h1>Hello, {student.fullName.split(' ')[0]}<span className="welcome-dot">.</span></h1><span>What would you like to work on today?</span></div><Link href={href('/dashboard?view=profile')} className="home-stage"><span>{stage.startsWith('ATS')?'ATSWA':'ICAN'}</span><strong>{stage}</strong><span aria-hidden="true">⌄</span></Link></header>
  <section className="home-feature" aria-roledescription="carousel" aria-label="Study suggestions"><div className="feature-copy" aria-live="polite"><span className="feature-tag">{feature.tag}</span><h2>{feature.title.split('\n').map((line,i)=><span key={i}>{line}</span>)}</h2><p>{feature.body}</p><a href={href(feature.destination)} className="feature-action">{feature.action}<span aria-hidden="true">→</span></a></div><div className="feature-art" aria-label="Reserved space for your banner artwork"><div><span className="art-mark" aria-hidden="true">↗</span><span>{feature.art}</span><small>Your artwork goes here</small></div></div><div className="feature-controls"><div className="feature-dots">{features.map((f,i)=><button key={f.tag} aria-label={`Show study suggestion ${i+1}`} aria-pressed={slide===i} onClick={()=>setSlide(i)}/>)}</div><div><button aria-label="Previous study suggestion" onClick={()=>setSlide((slide+2)%3)}>←</button><button aria-label="Next study suggestion" onClick={()=>setSlide((slide+1)%3)}>→</button></div></div></section>
  <div className="home-body"><div className="home-main">
   <section className="home-subjects" id="home-subjects"><div className="home-section-heading"><div><span className="section-kicker">YOUR CLASSROOM</span><h2>My subjects <small>{papers.length}</small></h2></div><Link href={href('/dashboard?view=subjects')}>View all <span aria-hidden="true">→</span></Link></div><label className="home-search"><span aria-hidden="true">⌕</span><input type="search" aria-label="Search my subjects" placeholder="Find a subject…" value={search} onChange={e=>setSearch(e.target.value)}/><span className="search-count">{stage}</span></label><div className="home-subject-grid">{filtered.map((paper,i)=>{const ids=new Set(state.topics.filter(t=>t.paperId===paper.id).map(t=>t.id));const done=progress.filter(p=>ids.has(p.topicId)&&p.status==='Okay').length;return <Link className={`home-subject tone-${i%4}`} key={paper.id} href={href(`/papers/${paper.id}`)}><div className="subject-cover"><span className="subject-code">{paper.code}</span><span className="cover-caption">SUBJECT IMAGE</span><span className="subject-arrow" aria-hidden="true">↗</span></div><div className="subject-info"><h3>{paper.name}</h3><p>{ids.size?`${ids.size} topics · ${done} confident`:'Topic plan coming soon'}</p><span className="subject-rule"><span style={{width:`${ids.size?done/ids.size*100:0}%`}}/></span></div></Link>;})}</div>{!filtered.length&&<p className="home-empty">{papers.length?'No matching subjects. Try a different name or code.':'Your subjects will appear here once you choose your papers.'}</p>}</section>
   <section className="home-continue"><div className="home-section-heading"><div><span className="section-kicker">KEEP YOUR MOMENTUM</span><h2>{recentPaper?'Continue learning':'Your first step'}</h2></div></div><div className="continue-card"><div className="continue-symbol" aria-hidden="true">▷</div><div><span>{recentPaper?.code??'START WITH ONE SUBJECT'}</span><h3>{recentTopic?.topicName??'Choose a topic. Make a start.'}</h3><p>{recentPaper?`${recentPaper.name} · ${recent?.status}`:'Your most recent study topic will appear here after your first update.'}</p></div><Link href={href(recentPaper?`/papers/${recentPaper.id}`:'#home-subjects')}>{recentPaper?'Continue':'Browse subjects'} <span aria-hidden="true">→</span></Link></div></section>
   <section className="home-practice"><div><span className="section-kicker">LEARN. TRY. TRY AGAIN.</span><h2>Ready to put it into practice?</h2><p>Find question materials and record your practice for each subject.</p><Link href={href('/dashboard?view=practice')}>Go to practice room <span aria-hidden="true">→</span></Link></div><div className="practice-cover" aria-label="Reserved practice illustration"><span aria-hidden="true">✓</span><small>PRACTICE IMAGE</small></div></section>
  </div><aside className="home-rail"><section className="home-week"><div className="rail-title"><span aria-hidden="true">▦</span><h2>This week</h2></div><p>A little structure goes a long way.</p>{weekly.length?<ul>{weekly.slice(0,3).map(p=>{const t=state.topics.find(t=>t.id===p.topicId);return <li key={p.id}><span aria-hidden="true">○</span><span>{t?.topicName??'Study topic'}<small>{p.status}</small></span></li>;})}</ul>:<div className="week-empty"><span aria-hidden="true">＋</span><strong>Make a plan for your week</strong><p>Add the topics you want to focus on. Start with two or three.</p></div>}<Link href={href('/dashboard?view=weekly')}>{weekly.length?'Review weekly plan':'Choose my priorities'} →</Link></section>
  <section className="home-snapshot"><span className="section-kicker">YOUR PREPARATION</span><h2>Every topic counts.</h2><div><strong>{confident}</strong><span>topics marked confident</span></div><div><strong>{progress.filter(p=>p.questionPractice!=='Not Yet').length}</strong><span>topics with practice recorded</span></div><Link href={href('/dashboard?view=report')}>View learning report →</Link><small>Based on your own study updates.</small></section>
  <section className="home-resource"><span>FROM ICAN</span><h3>Your syllabus. Your starting point.</h3><p>Find official study texts and examination insights for your stage.</p><Link href={href('/dashboard?view=resources')}>Explore resources ↗</Link></section></aside></div>
 </div>;
}
