"use client";
import Link from 'next/link';
import Image from 'next/image';
import { useState } from 'react';
import type { TrackerState } from '@/lib/types';
import { getStudent, getStudentPapers, getStudentProgress } from '@/lib/selectors';
import { stageFor } from '@/lib/stages';

const artwork=(name:string)=>/audit|assurance/i.test(name)?'magnifier':/tax/i.test(name)?'calculator':/case|business law/i.test(name)?'briefcase':/financial management|finance|economics/i.test(name)?'bars':'report';
function Art({name,hero=false}:{name:string;hero?:boolean}){return <Image src={`/brand/${name}.webp`} alt="" width={640} height={640} sizes={hero?'(max-width: 600px) 120px, 220px':'(max-width: 600px) 100px, 150px'} priority={hero} className="da-art"/>;}
export function StudentHomepage({state,studentId,preview=false}:{state:TrackerState;studentId:string;preview?:boolean}) {
 const [search,setSearch]=useState('');
 const student=getStudent(state,studentId); if(!student)return <p>Your profile could not be loaded.</p>;
 const papers=getStudentPapers(state,studentId), progress=getStudentProgress(state,studentId);
 const recent=[...progress].filter(p=>p.status!=='Not Started'||p.lastStudied).sort((a,b)=>(b.lastStudied??b.updatedAt).localeCompare(a.lastStudied??a.updatedAt))[0];
 const recentTopic=recent?state.topics.find(t=>t.id===recent.topicId):undefined;
 const recentPaper=recentTopic?papers.find(p=>p.id===recentTopic.paperId):undefined;
 const weekly=progress.filter(p=>p.thisWeek), completed=weekly.filter(p=>p.status==='Okay').length;
 const stage=stageFor(student.level)??student.level;
 const base=`/login?mode=preview&stage=${encodeURIComponent(stage)}`;
 const href=(url:string)=>{if(!preview||url.startsWith('#'))return url;if(url.startsWith('/papers/')){const [id,query]=url.slice(8).split('?');return `${base}&subject=${encodeURIComponent(id)}${query?'&'+query:''}`;}return url==='/dashboard?view=subjects'?'#da-subjects':url==='/dashboard?view=weekly'?'#da-week':url==='/dashboard?view=practice'?`${base}&view=practice`:'/login';};
 const percentFor=(id:string)=>{const ids=new Set(state.topics.filter(t=>t.paperId===id).map(t=>t.id));return ids.size?Math.round(progress.filter(p=>ids.has(p.topicId)&&p.status==='Okay').length/ids.size*100):0;};
 const resume=recentPaper&&recentTopic?`/papers/${recentPaper.id}?lesson=${encodeURIComponent(recentTopic.id)}`:'#da-subjects';
 const filtered=papers.filter(p=>`${p.name} ${p.code}`.toLowerCase().includes(search.trim().toLowerCase()));
 return <div className="learning-home da-home">
  <header className="da-welcome"><div><h1>Welcome back, {student.fullName.split(' ')[0]}</h1><p><strong>{stage}</strong><span/>{stage.startsWith('ATS')?'ATSWA':'ICAN'} Student</p></div><div className="da-header-actions"><label className="da-search"><span aria-hidden="true">⌕</span><input type="search" placeholder="Search your subjects…" aria-label="Search your subjects" value={search} onChange={e=>setSearch(e.target.value)}/></label><Link className="da-account" href={href('/dashboard?view=profile')} aria-label="Open my profile"><span>{student.fullName.charAt(0)}</span><b>{student.fullName.split(' ')[0]}</b></Link></div></header>
  <div className="da-top-grid"><section className="da-resume"><div className="da-resume-copy"><p className="da-eyebrow">{recentPaper?'Continue learning':'Your learning journey'}</p><h2>{recentTopic?.topicName??'Your next chapter starts here.'}</h2><p className="da-description">{recentPaper?`${stage} · ${recentPaper.name}`:'Choose a subject and take your first step.'}</p>{recentPaper&&<div className="da-progress-line"><progress max={100} value={percentFor(recentPaper.id)} aria-label="Subject confidence"/><span>{percentFor(recentPaper.id)}% confident</span></div>}<Link className="da-primary" href={href(resume)}><span aria-hidden="true">▷</span>{recentPaper?'Continue learning':'Explore my subjects'}<span aria-hidden="true">→</span></Link></div><div className="da-hero-art"><Art name="open-books" hero/></div></section>
  <section className="da-week" id="da-week"><p className="da-eyebrow">This week</p><h2>Weekly study plan</h2><div className="da-week-content"><div>{weekly.length?<ul>{weekly.slice(0,4).map(p=>{const t=state.topics.find(t=>t.id===p.topicId);return <li key={p.id}><span className={`da-check ${p.status==='Okay'?'is-done':''}`} aria-label={p.status==='Okay'?'Confident':'In progress'}>{p.status==='Okay'?'✓':''}</span><Link href={href(t?`/papers/${t.paperId}?lesson=${encodeURIComponent(t.id)}`:'/dashboard?view=weekly')}>{t?.topicName??'Study topic'}</Link></li>;})}</ul>:<p className="da-week-empty">Make room for a few priorities.<br/>Choose the topics you want to focus on this week.</p>}<Link className="da-text-link" href={preview&&!weekly.length?'#da-subjects':href('/dashboard?view=weekly')}>{weekly.length?'Review weekly plan':'Choose your topics'} <span aria-hidden="true">→</span></Link></div><div className="da-week-summary"><div className="da-ring" style={{background:`conic-gradient(#07563a ${weekly.length?completed/weekly.length*100:0}%, #b9e4e6 0)`}}><strong>{completed}/{weekly.length}</strong></div><b>Weekly goals</b><small>{weekly.length?`${completed} topics confident`:'Ready when you are'}</small></div></div></section></div>
  <div className="da-action-grid"><section className="da-promo da-practice"><div><h2>Practice questions</h2><p>Try five sample accounting questions at your own pace.</p><Link className="da-outline" href={href('/dashboard?view=practice')}>Start quiz <span aria-hidden="true">→</span></Link></div><Art name="checklist"/></section><section className="da-promo da-explore"><div><h2>Explore your subjects</h2><p>Your topics, study updates and learning resources.</p><Link className="da-outline" href={href('/dashboard?view=subjects')}>View all subjects <span aria-hidden="true">→</span></Link></div><Art name="books"/></section></div>
  <section id="da-subjects" className="da-subjects"><div className="da-section-title"><h2>My subjects</h2><Link href={href('/dashboard?view=subjects')}>View all subjects <span aria-hidden="true">→</span></Link></div><div className="da-subject-grid">{filtered.map((paper,i)=>{const percent=percentFor(paper.id);return <Link className={`da-subject da-tone-${i%4}`} key={paper.id} href={href(`/papers/${paper.id}`)}><div className="da-subject-art"><Art name={artwork(paper.name)}/></div><h3>{paper.name}</h3><p>{stage}</p><div className="da-progress-line"><progress max={100} value={percent} aria-label={`${paper.name}: topics confident`}/><span>{percent}%</span></div><span className="da-subject-open">Open subject <span aria-hidden="true">→</span></span></Link>;})}</div>{!filtered.length&&<p className="da-empty">{papers.length?'No matching subjects. Try another name or code.':'Your subjects will appear once you choose your papers.'}</p>}<p className="da-footnote">Progress reflects the topics you have marked confident.</p></section>
 </div>;
}
