"use client";
import Link from 'next/link';
import { useTracker } from './TrackerProvider';
import { PracticeRoom } from './PracticeRoom';
import { StudentSubjects } from './StudentSubjects';
import { StudentOverview } from './StudentOverview';
import { ThisWeekList } from './ThisWeekList';
import { PaperProgressRow } from './PaperProgressRow';
import { ManagePapers } from './ManagePapers';
import { getStudent, getStudentPapers, getStudentProgress } from '@/lib/selectors';
import { resourcesFor, stageFor, SUBJECTS } from '@/lib/stages';
export function StudentWorkspace({studentId,view='home'}:{studentId:string;view?:string}) {
 const {state}=useTracker();
 const student=getStudent(state,studentId); if(!student) return <p>Unable to load your profile. Please sign in again.</p>;
 const papers=getStudentPapers(state,studentId), progress=getStudentProgress(state,studentId);
 const stage=stageFor(student.level), stageLabel=stage??student.level;
 const names:Record<string,string>={home:'My learning space',subjects:'My subjects',weekly:'Weekly plan',practice:'Practice room',report:'Learning report',profile:'My profile',resources:'Study resources'};
 const selected=names[view]?view:'home';
 if(selected==='subjects')return <StudentSubjects state={state} studentId={studentId} managePapers={<ManagePapers studentId={studentId}/>}/>;
 return <div className="student-workspace"><div className={`workspace-toolbar ${selected==='home'?'home-toolbar-hidden':''}`}><div><span className="eyebrow">{stage?.startsWith('ATS')?'ATSWA':'ICAN'} / {stageLabel || 'Student'}</span><h1>{names[selected]}</h1></div><Link href="/dashboard?view=profile" className="student-avatar" aria-label="Open my profile">{student.fullName.split(' ').map(n=>n[0]).slice(0,2).join('')}</Link></div>
 {selected==='home' && <StudentOverview studentId={studentId}/>}
 {selected==='weekly' && <><p className="section-description">Choose your priorities and make time for the topics that need you most.</p><ThisWeekList studentId={studentId}/></>}
 {selected==='practice' && <><PracticeRoom/><div className="practice-banner"><div><span className="eyebrow">PUT YOUR LEARNING TO WORK</span><h2>Make practice part of the plan.</h2><p>Open a subject to record your question practice and topics to revisit.</p><a href={resourcesFor(student.level)} target="_blank" rel="noreferrer" className="primary-button">Find ICAN practice materials ↗</a></div><div className="image-slot practice-image"><span>PRACTICE IMAGE</span><small>Space for your artwork</small></div></div><div className="report-stats"><div><strong>{progress.filter(p=>p.questionPractice==='Attempted').length}</strong><span>Topics with questions attempted</span></div><div><strong>{progress.filter(p=>p.questionPractice==='Reattempt').length}</strong><span>Topics marked for another attempt</span></div></div><div className="paper-list-enhanced">{papers.map(p=><PaperProgressRow key={p.id} state={state} studentId={studentId} paper={p}/>)}</div><div className="empty-panel"><h3>Timed mock exams</h3><p>Your DIET team has not published timed exams yet. Topic practice tracking is available in each subject.</p></div></>}
 {selected==='report' && <><p className="section-description">A clear view of the preparation you have recorded. Confidence is self-reported, not an exam score.</p><div className="report-stats">{(['Okay','Learning','Needs Practice','Not Started'] as const).map(status=><div key={status}><strong>{progress.filter(p=>p.status===status).length}</strong><span>{status==='Okay'?'Feeling confident':status}</span></div>)}</div><section className="report-panel"><h2>Subject progress</h2>{papers.map(p=>{const topics=state.topics.filter(t=>t.paperId===p.id);const ids=new Set(topics.map(t=>t.id));const confident=progress.filter(r=>ids.has(r.topicId)&&r.status==='Okay').length;const percent=topics.length?Math.round(confident/topics.length*100):0;return <Link href={`/papers/${p.id}`} className="report-row" key={p.id}><div><b>{p.name}</b><small>{topics.length?`${confident} of ${topics.length} topics marked confident`:'Topic list awaiting publication'}</small></div><progress value={percent} max={100} aria-label={`${p.name} confidence`}/><strong>{percent}%</strong></Link>;})}</section></>}
 {selected==='profile' && <section className="profile-panel"><span className="eyebrow">YOUR STUDENT ACCOUNT</span><h2>{student.fullName}</h2><dl className="profile-review"><div><dt>First name</dt><dd>{student.fullName.split(' ')[0]}</dd></div><div><dt>Last name</dt><dd>{student.fullName.split(' ').slice(1).join(' ')||'—'}</dd></div><div><dt>Email</dt><dd>{student.email}</dd></div><div><dt>Exam stage</dt><dd>{stageLabel||'Not set'}</dd></div><div><dt>Exam diet</dt><dd>{student.examDiet||'Not set yet'}</dd></div><div><dt>Active subjects</dt><dd>{papers.length}</dd></div></dl><p>Need to correct your name or move to another stage? Contact your DIET coordinator so your saved progress stays connected to your account.</p><ManagePapers studentId={studentId}/></section>}
 {selected==='resources' && <><p className="section-description">Official learning materials for {stageLabel}. Links open on ICAN’s website.</p><a className="resource-card" href={resourcesFor(student.level)} target="_blank" rel="noreferrer"><span>ICAN</span><div><h2>Study texts & examination insights</h2><p>Find official resources and past examination materials for your stage.</p></div><b>↗</b></a><section className="report-panel"><h2>Your syllabus subjects</h2><ol className="syllabus-list">{stage && SUBJECTS[stage].map(([code,name])=><li key={code}><b>{code}</b><span>{name}</span></li>)}</ol><p className="field-hint">Based on ICAN’s current professional syllabus and ATSWA syllabus effective September 2026.</p></section></>}
 </div>;
}
