"use client";
import { useState } from 'react';
import Link from 'next/link';
import { resourcesFor } from '@/lib/stages';
import type { Paper, Topic, TopicProgress, TopicStatus, QuestionPractice } from '@/lib/types';

export function SubjectLearning({paper,topics,progress,level,backHref,onUpdate,preview=false}:{paper:Paper;topics:Topic[];progress:TopicProgress[];level:string;backHref:string;onUpdate:(id:string,patch:Partial<TopicProgress>)=>void;preview?:boolean}) {
 const [section,setSection]=useState<'chapters'|'resources'>('chapters');
 const [query,setQuery]=useState('');
 const visible=topics.filter(t=>t.topicName.toLowerCase().includes(query.trim().toLowerCase()));
 const confident=progress.filter(p=>topics.some(t=>t.id===p.topicId)&&p.status==='Okay').length;
 return <div className="subject-learning">
  <Link className="subject-back" href={backHref}>← Back to my subjects</Link>
  <header className="subject-hero"><div><span className="subject-eyebrow">{level} · {paper.code}</span><h1>{paper.name}</h1><p>Your topic plan, study updates and learning resources.</p><div className="subject-meta"><span>{topics.length} topics</span><span>{confident} marked confident</span></div></div><div className="subject-art" aria-label="Reserved subject image">SUBJECT IMAGE</div></header>
  <div className="subject-layout"><div>
   <nav className="subject-tabs" aria-label="Subject sections"><button aria-pressed={section==='chapters'} onClick={()=>setSection('chapters')}>Chapters & topics</button><button aria-pressed={section==='resources'} onClick={()=>setSection('resources')}>Learning resources</button></nav>
   {section==='chapters'?<section aria-label="Chapters and topics"><div className="subject-section-head"><h2>Your study plan</h2><span>{topics.length} topics</span></div><label className="subject-search">Find a topic<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search within this subject"/></label>
    {topics.length>0?<><p className="subject-note">Starter topic plan. Full syllabus chapters and lesson materials will be added by the DIET team.</p><details className="chapter-block" open><summary><span className="chapter-number">01</span><span><strong>Study topics</strong><small>{visible.length} matching topics</small></span></summary><div className="chapter-topics">{visible.map((topic)=>{const p=progress.find(p=>p.topicId===topic.id);return <details className="learning-topic" key={topic.id}><summary><span className="topic-index">{String(topics.indexOf(topic)+1).padStart(2,'0')}</span><strong>{topic.topicName}</strong><span className={`topic-state ${p?.status==='Okay'?'confident':''}`}>{p?.status==='Okay'?'Confident':p?.status??'Not Started'}</span></summary><div className="topic-content"><div className="topic-material-note"><strong>Lesson materials coming soon</strong><p>You can use the official ICAN study texts while DIET lessons and notes are being prepared.</p><a href={resourcesFor(level)} target="_blank" rel="noreferrer">Find official study materials ↗</a></div>{p?<fieldset className="topic-progress-fields"><legend>{preview?'Try a study update · preview only':'Your study update'}</legend><label>Preparation status<select value={p.status} onChange={e=>onUpdate(p.id,{status:e.target.value as TopicStatus})}>{['Not Started','Learning','Needs Practice','Okay'].map(s=><option key={s} value={s}>{s==='Okay'?'Confident':s}</option>)}</select></label><label>Question practice<select value={p.questionPractice} onChange={e=>onUpdate(p.id,{questionPractice:e.target.value as QuestionPractice})}>{['Not Yet','Attempted','Reattempt'].map(s=><option key={s}>{s}</option>)}</select></label><label>Last studied<input type="date" value={p.lastStudied??''} onChange={e=>onUpdate(p.id,{lastStudied:e.target.value||null})}/></label><label>Next step<input value={p.nextStep} placeholder="What will you work on next?" onChange={e=>onUpdate(p.id,{nextStep:e.target.value})}/></label><label className="topic-week"><input type="checkbox" checked={p.thisWeek} onChange={e=>onUpdate(p.id,{thisWeek:e.target.checked})}/> Add to this week’s plan</label></fieldset>:<p className="subject-note">Your study record is not available yet. Refresh the page to try again.</p>}</div></details>})}{!visible.length&&<p className="subject-empty">No topics match your search. Try a different word.</p>}</div></details></>:<div className="subject-empty"><h3>Your subject is ready.</h3><p>The chapter and topic plan is being prepared. You can explore the official study materials now.</p><button className="subject-primary" onClick={()=>setSection('resources')}>Explore learning resources</button></div>}
   </section>:<section aria-label="Learning resources"><div className="subject-section-head"><h2>Learning resources</h2></div><article className="resource-available"><span className="subject-eyebrow">OFFICIAL ICAN MATERIALS</span><h3>Study texts & examination resources</h3><p>Open the ICAN learning materials page and choose {paper.name} for {level}. Check the syllabus and examination diet shown on each resource.</p><a className="subject-primary" href={resourcesFor(level)} target="_blank" rel="noreferrer">Open ICAN resources ↗</a></article><div className="subject-resource-grid">{['Video lessons','DIET summary notes','Practice questions'].map(title=><article key={title}><span className="resource-placeholder">RESOURCE IMAGE</span><h3>{title}</h3><p>Not published yet</p></article>)}</div></section>}
  </div><aside className="subject-side"><section><span className="subject-eyebrow">YOUR PREPARATION</span><h2>{confident}<small> / {topics.length}</small></h2><p>topics marked confident</p><progress aria-label="Topics marked confident" value={confident} max={topics.length||1}/><small>Based on your own study updates.</small></section><section><h3>A manageable next step</h3><p>Choose one topic, review your study text, then record what you need to practise.</p><button onClick={()=>{setSection('chapters');setQuery('');}}>View topic plan</button></section>{preview&&<p className="subject-note">Sample account. Changes here are temporary and are not saved to a student profile.</p>}</aside></div>
 </div>;
}
